/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'metricsOverview': MotiaStream<{ totalRequests24h: number; totalRequests30d: number; totalRequests90d: number; totalRequestsAllTime: number; currentRps: number; errorRate: number; uptime30d: number; updatedAt: string }>
    'metricsByChain': MotiaStream<{ chain: string; env: string; region: string; requests24h: number; currentRps: number; errorRate: number; latencyP50: number; latencyP95: number; updatedAt: string }>
  }

  interface Handlers {
    'RefreshRpcMetrics': CronHandler<never>
    'GetProjectMetricsOverview': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { projectId: string; requests30d: number; requests24h: number; currentRps: number; updatedAt: string; topChains: Array<{ chain: string; requests: number }> }> | ApiResponse<404, { error: string; message: string }>, never>
    'GetMetricsTimeseries': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { chain: string; env: string; resolution: '5s' | '1m' | '5m'; points: Array<{ ts: string; requests: number; errors: number; latencyP95: number }> }>, never>
    'GetMetricsOverview': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { totalRequests24h: number; totalRequests30d: number; totalRequests90d: number; totalRequestsAllTime: number; currentRps: number; errorRate: number; uptime30d: number; updatedAt: string; window: { from: string; to: string } }>, never>
    'GetMetricsByChain': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { env: string; generatedAt: string; items: Array<{ chain: string; env: string; region: string; requests24h: number; currentRps: number; errorRate: number; latencyP50: number; latencyP95: number; updatedAt: string }> }>, never>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'ClickHouseHealthCheck': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { ok: boolean; latencyMs: number; timestamp: string }>, never>
    'ListClickHouseTableSchema': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { table: string; columns: Array<{ name: string; type: string; defaultKind: string | unknown; comment: string | unknown }> }>, never>
    'RefreshMetricsNow': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; message: string; overview?: unknown }>, never>
    'GetStreamData': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { metricsOverview: unknown | unknown; metricsByChain: unknown | unknown }>, never>
  }
}